[package]
name = "rmenu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
font-kit = "0.7"
pathfinder_geometry = "0.5"
smithay-client-toolkit = "0.15"
wayland-client = "0.29"
env_logger = "0.8"
raqote = "0.8"
log = "0.4"