name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: "rust:1.73"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        apt-get update
        apt-get install --yes --no-install-recommends libxkbcommon-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
